# Default values for config-init.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# fullnameOverride give this job your prefered name
fullnameOverride: ""

configJob:
  replicaCount: 1

  image: gluufederation/config-init
  tag: 4.0.0_dev
  restartPolicy: Never
  args: ["load"]

  persistence:
    enabled: true
    mounts:         # Define volume mounts and volumes.
      - mountPath: /opt/config-init/db/
        name: config
      - mountPath: /opt/config-init/db/generate.json
        name: mount-generate-conf-file
        subPath: generate.json
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: config-pvc # TODO: use PVC name here
    - name: mount-generate-conf-file
      configMap:
        name: generate-conf-file-cm #this should reflect name of cm with json data
  envFrom:
    - configMapRef:
      name: name #{{ .Release.Name }}-{{ .Chart.Name }} #fullname template defines the names like this

jsonFileDataCm:
  name: generate-conf-file-cm       #name of cm with json data
  items:
    generate.json: |-
      {
          "hostname": "demoexample.gluu.org",
          "country_code": "US",
          "state": "TX",
          "city": "Austin",
          "admin_pw": "S3cr3t+pass",
          "email": "s@gluu.local",
          "org_name": "Gluu Inc."
      }
      