{{- template "common.persistentvolume" ( list . "mychart.persistentvolume" ) }}
{{- define "mychart.persistentvolume" -}}
metadata:
  name: {{template "ldap.fullname" . }}
spec:
  claimRef:
    name: opendj-pvc
    namespace: {{ .Release.Namespace }}
{{- end -}}