{{- template "common.persistentvolumeclaim" ( list . "ldap.persistentvolumeclaim" ) }}
{{- define "ldap.persistentvolumeclaim" -}}
metadata:
  name: opendj-pvc
spec:
  selector:
    matchLabels:
      pvc: opendj-pvc
{{- end -}}