{{- template "common.service" ( list . "ldap.service" ) -}}
{{- define "ldap.service" -}}
metadata:
  name: {{ .Values.global.ldap.serviceName }}
  labels: 
    app: opendj

spec:
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      type: TCP
      name: {{ $key }}
    {{- end }}
  selector:
    app: opendj
  
  {{- end -}}
  