apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "oxauth.fullname" . }}
  labels:
    app: oxauth
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oxauth
  template:
    metadata:
      labels:
        app: oxauth
    spec:
      containers:
      - name: {{ include "oxauth.name" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - configMapRef:
            name: {{ template "oxauth.fullname" . }}
        volumeMounts:
        {{- range $key, $value := .Values.volumeMounts }}
          - mountPath: {{ $value.mountPath }}
            name: {{ $value.name }}
            subPath: {{ $key }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 25
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ .Values.global.domain }}
      volumes:
      - name: oxauth-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-oxauth
