# Default values for oxauth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gluufederation/oxauth
  tag: 4.0.0_dev
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  storageClass: "-"
  accessMode: ReadWriteOnce
  size: 10M
  # please uncomment and provide your own claim if you have set up one
  # existingClaim: ""

#VolumeMounts
volumeMounts:
  logs:
    mountPath: /data/oxauth/logs
    name: oxauth-volume
  ext:
    mountPath: /data/oxauth/lib/ext
    name: oxauth-volume
  static:
    mountPath: /data/oxauth/custom/static
    name: oxauth-volume
  pages:
    mountPath: /data/oxauth/custom/pages
    name: oxauth-volume

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi # 1536Mi
  requests:
   cpu: 100m
   memory: 128Mi # 1000Mi

nodeSelector: {}

tolerations: []

affinity: {}
